#!/bin/bash

#update
if [ -n "$1" ]; then

	if [ ! -d "./sites/$1" ]; then

		echo "Could not find site to update!"	
		echo "Make sure it exists in the sites directory!"
	
	else

		#Redeploy any changes to sites/$1
		last=`du -shb ./sites/$1/assets`

		while [ "true" ]
		do
			first=`du -shb ./sites/$1/assets`

			if [ "$first" != "$last" ]
			then
				cp -r ./sites/Elastic-Core/assets ./live
				cp -r ./sites/$1/assets ./live

				last=$first
	
				echo "Assets Updated!"
			fi

			sleep 2
		done
	fi
else

	echo "./update <site>"

fi
